### ISSUE TITLE
[Npm] Lets make vjs a public repo and publish it to npm

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/vjs#180]
yeey!

**Comment by jimdebeer** [comment]
need to figure out a name on npm vjs is taken ofc

**Comment by ninjatux** [comment]
man is under your name...[vjs](https://www.npmjs.com/package/vjs)
you already published vjs!!

**Comment by shawninder** [comment]
@ninjatux : I published vjs to npm using Jim's account (at his request). He didn't do it himself so he may not even remember.. @jimdebeer : problem solved

**Comment by jimdebeer** [comment]
i think we may be rdy to push the first master version for npm (then the native guys can use it and dont have to link)
