### ISSUE TITLE
[Context] [Operator] Error in contextEmitter when using cache

### ISSUE THREAD

**Issue by youzi** [vigour-io/vjs#206]
```
        if (contextInstances) {
          for (var i = 0, length = contextInstances.length; i < length; i++) {
            instance = contextInstances[i]
            for (var j = path.length - 1; j >= 0; j--) {
              property = path[j]
              instance = instance[property] <===== can not set prop of undefined
            }
            if (instance) {
              if (instance._on && instance._on[emitter.key] === emitter) {
                emitter.push(instance, event)
                instance.emitContext(emitter, data, event)
              }
            }
          }
        }
```

**Comment by aphorise** [comment]
That for-loop looks odd & nasty - especially as there is only one __recent__ exception in the whole `for-loop` scheme of things where it can fit mainly the `lhskind` type operations as described in:  
[ecma-262 v6.0- Runtime Semantics: ForIn/OfBodyEvaluation (lhs, stmt, iterator, lhsKind, labelSet)](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-runtime-semantics-forin-div-ofbodyevaluation-lhs-stmt-iterator-lhskind-labelset)
^^^ which is also the most complex and condition filled of the lot and was not part of earlier specifications < June 2015

Typically one would expect no greater than three / tri-composit makeup eg: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for

**Comment by jimdebeer** [comment]
hey mehdi you mean the if  `instance` block right ? you have to do this check with an extra for loop unfortunately --- the only problem in here is that this error ` <===== can not set prop of undefined`  should not happen ever -- so im pretty happy it crashed ;) `instance = contextInstances[i]` should always return something here -- i also did some tests on perf here (its a super critical for loop)  and using a nested loop is fastest -- just needs lets everywhere

**Comment by jimdebeer** [comment]
we can not use custom iterators or anything fancy es6 for this since it will be transpiled to 10 times slower code for es5 devices (all front ends)

**Comment by aphorise** [comment]
@jimdebeer yes I was refering to:
```
 for (var i = 0, length = contextInstances.length; i < length; i++) {
```
^^^ that nasty-ness ^^^  :do_not_litter:

**Comment by jimdebeer** [comment]
this is the way i always do for loops --  for (var i = 0, length = contextInstances.length; i < length; i++) {
 give me one thing thats wrongf with this? this is js btw

**Comment by jimdebeer** [comment]
https://jsperf.com/for-loop-vs-for-in-loop/8
