### ISSUE TITLE
[config] configuration via environment variables

### ISSUE THREAD

**Issue by shawninder** [vigour-io/vjs#208]
Perhaps the name of the environment variable attached to a specific configured value could be `<pacakge.json[name]>.camelToUpperCase()_<varName>.camelToUpperCase()` such that if I have `package.json[name] = 'service'` and `package.json[vigour.startMessage] = { ... }`, the environment variable capable of changing that value would be `SERVICE_START_MESSAGE`. Not too sure how nice this is... Perhaps the apparent standard of having strictly upper cased environment variable names is not important enough to preserve to justify this and `service_startMessage` would be sufficient...

**Comment by shawninder** [comment]
I have a (failing) test for this desired behaviour if it can be of any use: https://github.com/vigour-io/service/blob/master/test/node/index.js#L25

**Comment by marcusbesjes** [comment]
On initialisation of a `new Config()`, the constructor will check for any `env` fields, and try to replace the `val` with the environment variable with that (value of `env`) name.

```json
{
  "vigour": {
    "defaultResponse": {
      "val": "this is default respunt!",
      "env": "TSERVICE_DEFRESPONSE"
    }
  }
```

In the example above, where ever `TSERVICE_DEFRESPONSE` environment variable is set, `config.defaultResponse` will hold its value.

**Comment by marcusbesjes** [comment]
this is implemented

**Comment by shawninder** [comment]
Looks like it's working aka my test passes (https://github.com/vigour-io/service/commit/14556650f4124f9b2a9a6375bc20da5724d8676d)
