### ISSUE TITLE
[Config] Extra config in separate files

### ISSUE THREAD

**Issue by marcusbesjes** [vigour-io/vjs#210]
on initialisation of a `new Config()`, the constructor should check for a `configFiles` field, and attempt to require and merge the files specified into itself.

**Comment by marcusbesjes** [comment]
@shawninder , having config coming from other files than the `package.json` needs work in DOWHAP since it would also need to watch these other config files.

I will implement reading files in config now, but watching them in DOWHAP will require more work. Lets discuss how important this feature is, by going over some usecases.

**Comment by marcusbesjes** [comment]
@shawn it's implemented so that its possible to point to files for additional config, but this will not be handled / watched / relaunched by DOWHAP (yet). Please review the updated tests and close the issue if satisfied

**Comment by shawninder** [comment]
This looks like it works enough for my needs, closing
