### ISSUE TITLE
[Config] Fails with arrays

### ISSUE THREAD

**Issue by shawninder** [vigour-io/vjs#212]
Passing arrays to this config stuff completely fails. `.val` returns `false` instead of the array I originally passed. This is probably due to vjs not handling arrays, but I would at least expect an array-like object, not `false`.

**Comment by shawninder** [comment]
As an example:
```
var Config = require('vjs/lib/config')
var config = new Config({
  manip: [
    'boom'
  ]
})
console.log(config.manip.val)
```
logs

```
false
```

whereas
```

{ '0': { _parent: [Circular], key: '0', _input: 'boom' },
  _parent: { manip: [Circular] },
  key: 'manip' }
```
logs
```
var Base = require('vjs/lib/base')
var base = new Base({
  manip: [
    'boom'
  ]
})
console.log(base.manip.val)
```

**Comment by shawninder** [comment]
I added tests for this and other foreseeable problems: https://github.com/vigour-io/vjs/commit/d5d24f070c0ee53ee9b6cedcc4fcd32970cbafca

**Comment by marcusbesjes** [comment]
I'll check this out

**Comment by jimdebeer** [comment]
small reminder vjs does not work with arrays if you want array to be
skipped you need to enhance the set method and not qualify arrays as objects

**Comment by marcusbesjes** [comment]
Arrays will just be interpreted as Objects with numerical keys for now
